### ISSUE TITLE
Update README with project vision 

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/ae#4]
Add a section to the README that gives vision to the project.

**Comment by daily-fred** [comment]
Hi! - This is my first comment and I am just learning to use `git` and GitHub so... :partying_face: 

I have rewritten the README.md in a fork of this project in my [`readme-rewrite`](https://github.com/daily-fred/ae/tree/readme-rewrite) branch and wanted to ask if it fits in here.

I actually don't know if that "solves" #4, maybe someone can give me some feedback. If it is unwanted or unnecessary, just let me know.

**Cheers!**

**Comment by dmah42** [comment]
can you create a pull request from your branch to the project? that way, you can get feedback from us directly on the changes, and we can merge it in when it's ready.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
