### ISSUE TITLE
subcommand: allocate

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/ae#9]
See the "Allocate" runtime verb in https://github.com/aurae-runtime/aurae/blob/main/api/v0/runtime.proto

Create a subcommand to match the readme. Does not have to "work" just needs the plumbing in place.

**Comment by palash25** [comment]
hi @krisnova 👋🏽 i would like to pick this up. I have a question though, i see that aurae does not generated go code for the proto definitions https://github.com/aurae-runtime/aurae/blob/main/buf.gen.yaml  does generating go code for the protobuf api also come under the scope of this issue? if yes will the generate go code be a part of the aurae repo and this issue will require two separate PRs one to aurae repo adding the generated code and one to this repo adding the command and client side code?
